name: Build Cross-Platform Releases

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for Linux
      if: matrix.os == 'ubuntu-latest'
      run: npm run build:linux
      
    - name: Build for Windows
      if: matrix.os == 'windows-latest'
      run: npm run build:win
      
    - name: Build for macOS
      if: matrix.os == 'macos-latest'
      run: npm run build:mac
      
    - name: Upload Linux artifacts
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: agenttradr-linux
        path: dist/*.AppImage
        
    - name: Upload Windows artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: agenttradr-windows
        path: dist/*.exe
        
    - name: Upload macOS artifacts
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: agenttradr-macos
        path: dist/*.dmg

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          agenttradr-linux/*
          agenttradr-windows/*
          agenttradr-macos/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}